version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      - npm i -g @vue/cli
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo nothing to do
artifacts:
  files:
    - '**/*'
  base-directory: dist
