version: 0.2

phases:
  install:
    commands:
      - npm install i
  pre_build:
    commands:
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo nothing to do
artifacts:
  files:
    - '**/*'
  base-directory: dist
