version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo nothing to do
      - zip -r dist.zip dist
artifacts:
  # files:
  #   - '**/*'
  files:
    - dist.zip
    - appspec.yml
    - scripts/*
